export const countryOptions = [
  { label: 'Afghanistan', value: 'AF', code: '004' },
  { label: 'Åland Islands', value: 'AX', code: '248' },
  { label: 'Albania', value: 'AL', code: '008' },
  { label: 'Algeria', value: 'DZ', code: '012' },
  { label: 'American Samoa', value: 'AS', code: '016' },
  { label: 'Andorra', value: 'AD', code: '020' },
  { label: 'Angola', value: 'AO', code: '024' },
  { label: 'Anguilla', value: 'AI', code: '660' },
  { label: 'Antarctica', value: 'AQ', code: '010' },
  { label: 'Antigua and Barbuda', value: 'AG', code: '028' },
  { label: 'Argentina', value: 'AR', code: '032' },
  { label: 'Armenia', value: 'AM', code: '051' },
  { label: 'Aruba', value: 'AW', code: '533' },
  { label: 'Australia', value: 'AU', code: '036' },
  { label: 'Austria', value: 'AT', code: '040' },
  { label: 'Azerbaijan', value: 'AZ', code: '031' },
  { label: 'Bahamas', value: 'BS', code: '044' },
  { label: 'Bahrain', value: 'BH', code: '048' },
  { label: 'Bangladesh', value: 'BD', code: '050' },
  { label: 'Barbados', value: 'BB', code: '052' },
  { label: 'Belarus', value: 'BY', code: '112' },
  { label: 'Belgium', value: 'BE', code: '056' },
  { label: 'Belize', value: 'BZ', code: '084' },
  { label: 'Benin', value: 'BJ', code: '204' },
  { label: 'Bermuda', value: 'BM', code: '060' },
  { label: 'Bhutan', value: 'BT', code: '064' },
  {
    label: 'Bolivia, Plurinational State of',
    value: 'BO',
    code: '068'
  },
  {
    label: 'Bonaire, Sint Eustatius and Saba',
    value: 'BQ',
    code: '535'
  },
  { label: 'Bosnia and Herzegovina', value: 'BA', code: '070' },
  { label: 'Botswana', value: 'BW', code: '072' },
  { label: 'Bouvet Island', value: 'BV', code: '074' },
  { label: 'Brazil', value: 'BR', code: '076' },
  {
    label: 'British Indian Ocean Territory',
    value: 'IO',
    code: '086'
  },
  { label: 'Brunei Darussalam', value: 'BN', code: '096' },
  { label: 'Bulgaria', value: 'BG', code: '100' },
  { label: 'Burkina Faso', value: 'BF', code: '854' },
  { label: 'Burundi', value: 'BI', code: '108' },
  { label: 'Cabo Verde', value: 'CV', code: '132' },
  { label: 'Cambodia', value: 'KH', code: '116' },
  { label: 'Cameroon', value: 'CM', code: '120' },
  { label: 'Canada', value: 'CA', code: '124' },
  { label: 'Cayman Islands', value: 'KY', code: '136' },
  { label: 'Central African Republic', value: 'CF', code: '140' },
  { label: 'Chad', value: 'TD', code: '148' },
  { label: 'Chile', value: 'CL', code: '152' },
  { label: 'China', value: 'CN', code: '156' },
  { label: 'Christmas Island', value: 'CX', code: '162' },
  { label: 'Cocos (Keeling) Islands', value: 'CC', code: '166' },
  { label: 'Colombia', value: 'CO', code: '170' },
  { label: 'Comoros', value: 'KM', code: '174' },
  { label: 'Congo', value: 'CG', code: '178' },
  {
    label: 'Congo, Democratic Republic of the',
    value: 'CD',
    code: '180'
  },
  { label: 'Cook Islands', value: 'CK', code: '184' },
  { label: 'Costa Rica', value: 'CR', code: '188' },
  { label: "Côte d'Ivoire", value: 'CI', code: '384' },
  { label: 'Croatia', value: 'HR', code: '191' },
  { label: 'Cuba', value: 'CU', code: '192' },
  { label: 'Curaçao', value: 'CW', code: '531' },
  { label: 'Cyprus', value: 'CY', code: '196' },
  { label: 'Czechia', value: 'CZ', code: '203' },
  { label: 'Denmark', value: 'DK', code: '208' },
  { label: 'Djibouti', value: 'DJ', code: '262' },
  { label: 'Dominica', value: 'DM', code: '212' },
  { label: 'Dominican Republic', value: 'DO', code: '214' },
  { label: 'Ecuador', value: 'EC', code: '218' },
  { label: 'Egypt', value: 'EG', code: '818' },
  { label: 'El Salvador', value: 'SV', code: '222' },
  { label: 'Equatorial Guinea', value: 'GQ', code: '226' },
  { label: 'Eritrea', value: 'ER', code: '232' },
  { label: 'Estonia', value: 'EE', code: '233' },
  { label: 'Eswatini', value: 'SZ', code: '748' },
  { label: 'Ethiopia', value: 'ET', code: '231' },
  {
    label: 'Falkland Islands (Malvinas)',
    value: 'FK',
    code: '238'
  },
  { label: 'Faroe Islands', value: 'FO', code: '234' },
  { label: 'Fiji', value: 'FJ', code: '242' },
  { label: 'Finland', value: 'FI', code: '246' },
  { label: 'France', value: 'FR', code: '250' },
  { label: 'French Guiana', value: 'GF', code: '254' },
  { label: 'French Polynesia', value: 'PF', code: '258' },
  {
    label: 'French Southern Territories',
    value: 'TF',
    code: '260'
  },
  { label: 'Gabon', value: 'GA', code: '266' },
  { label: 'Gambia', value: 'GM', code: '270' },
  { label: 'Georgia', value: 'GE', code: '268' },
  { label: 'Germany', value: 'DE', code: '276' },
  { label: 'Ghana', value: 'GH', code: '288' },
  { label: 'Gibraltar', value: 'GI', code: '292' },
  { label: 'Greece', value: 'GR', code: '300' },
  { label: 'Greenland', value: 'GL', code: '304' },
  { label: 'Grenada', value: 'GD', code: '308' },
  { label: 'Guadeloupe', value: 'GP', code: '312' },
  { label: 'Guam', value: 'GU', code: '316' },
  { label: 'Guatemala', value: 'GT', code: '320' },
  { label: 'Guernsey', value: 'GG', code: '831' },
  { label: 'Guinea', value: 'GN', code: '324' },
  { label: 'Guinea-Bissau', value: 'GW', code: '624' },
  { label: 'Guyana', value: 'GY', code: '328' },
  { label: 'Haiti', value: 'HT', code: '332' },
  {
    label: 'Heard Island and McDonald Islands',
    value: 'HM',
    code: '334'
  },
  { label: 'Holy See', value: 'VA', code: '336' },
  { label: 'Honduras', value: 'HN', code: '340' },
  { label: 'Hong Kong', value: 'HK', code: '344' },
  { label: 'Hungary', value: 'HU', code: '348' },
  { label: 'Iceland', value: 'IS', code: '352' },
  { label: 'India', value: 'IN', code: '356' },
  { label: 'Indonesia', value: 'ID', code: '360' },
  { label: 'Iran, Islamic Republic of', value: 'IR', code: '364' },
  { label: 'Iraq', value: 'IQ', code: '368' },
  { label: 'Ireland', value: 'IE', code: '372' },
  { label: 'Isle of Man', value: 'IM', code: '833' },
  { label: 'Israel', value: 'IL', code: '376' },
  { label: 'Italy', value: 'IT', code: '380' },
  { label: 'Jamaica', value: 'JM', code: '388' },
  { label: 'Japan', value: 'JP', code: '392' },
  { label: 'Jersey', value: 'JE', code: '832' },
  { label: 'Jordan', value: 'JO', code: '400' },
  { label: 'Kazakhstan', value: 'KZ', code: '398' },
  { label: 'Kenya', value: 'KE', code: '404' },
  { label: 'Kiribati', value: 'KI', code: '296' },
  {
    label: "Korea, Democratic People's Republic of",
    value: 'KP',
    code: '408'
  },
  { label: 'Korea, Republic of', value: 'KR', code: '410' },
  { label: 'Kuwait', value: 'KW', code: '414' },
  { label: 'Kyrgyzstan', value: 'KG', code: '417' },
  {
    label: "Lao People's Democratic Republic",
    value: 'LA',
    code: '418'
  },
  { label: 'Latvia', value: 'LV', code: '428' },
  { label: 'Lebanon', value: 'LB', code: '422' },
  { label: 'Lesotho', value: 'LS', code: '426' },
  { label: 'Liberia', value: 'LR', code: '430' },
  { label: 'Libya', value: 'LY', code: '434' },
  { label: 'Liechtenstein', value: 'LI', code: '438' },
  { label: 'Lithuania', value: 'LT', code: '440' },
  { label: 'Luxembourg', value: 'LU', code: '442' },
  { label: 'Macao', value: 'MO', code: '446' },
  { label: 'Madagascar', value: 'MG', code: '450' },
  { label: 'Malawi', value: 'MW', code: '454' },
  { label: 'Malaysia', value: 'MY', code: '458' },
  { label: 'Maldives', value: 'MV', code: '462' },
  { label: 'Mali', value: 'ML', code: '466' },
  { label: 'Malta', value: 'MT', code: '470' },
  { label: 'Marshall Islands', value: 'MH', code: '584' },
  { label: 'Martinique', value: 'MQ', code: '474' },
  { label: 'Mauritania', value: 'MR', code: '478' },
  { label: 'Mauritius', value: 'MU', code: '480' },
  { label: 'Mayotte', value: 'YT', code: '175' },
  { label: 'Mexico', value: 'MX', code: '484' },
  {
    label: 'Micronesia, Federated States of',
    value: 'FM',
    code: '583'
  },
  { label: 'Moldova, Republic of', value: 'MD', code: '498' },
  { label: 'Monaco', value: 'MC', code: '492' },
  { label: 'Mongolia', value: 'MN', code: '496' },
  { label: 'Montenegro', value: 'ME', code: '499' },
  { label: 'Montserrat', value: 'MS', code: '500' },
  { label: 'Morocco', value: 'MA', code: '504' },
  { label: 'Mozambique', value: 'MZ', code: '508' },
  { label: 'Myanmar', value: 'MM', code: '104' },
  { label: 'Namibia', value: 'NA', code: '516' },
  { label: 'Nauru', value: 'NR', code: '520' },
  { label: 'Nepal', value: 'NP', code: '524' },
  {
    label: 'Netherlands, Kingdom of the',
    value: 'NL',
    code: '528'
  },
  { label: 'New Caledonia', value: 'NC', code: '540' },
  { label: 'New Zealand', value: 'NZ', code: '554' },
  { label: 'Nicaragua', value: 'NI', code: '558' },
  { label: 'Niger', value: 'NE', code: '562' },
  { label: 'Nigeria', value: 'NG', code: '566' },
  { label: 'Niue', value: 'NU', code: '570' },
  { label: 'Norfolk Island', value: 'NF', code: '574' },
  { label: 'North Macedonia', value: 'MK', code: '807' },
  { label: 'Northern Mariana Islands', value: 'MP', code: '580' },
  { label: 'Norway', value: 'NO', code: '578' },
  { label: 'Oman', value: 'OM', code: '512' },
  { label: 'Pakistan', value: 'PK', code: '586' },
  { label: 'Palau', value: 'PW', code: '585' },
  { label: 'Palestine, State of', value: 'PS', code: '275' },
  { label: 'Panama', value: 'PA', code: '591' },
  { label: 'Papua New Guinea', value: 'PG', code: '598' },
  { label: 'Paraguay', value: 'PY', code: '600' },
  { label: 'Peru', value: 'PE', code: '604' },
  { label: 'Philippines', value: 'PH', code: '608' },
  { label: 'Pitcairn', value: 'PN', code: '612' },
  { label: 'Poland', value: 'PL', code: '616' },
  { label: 'Portugal', value: 'PT', code: '620' },
  { label: 'Puerto Rico', value: 'PR', code: '630' },
  { label: 'Qatar', value: 'QA', code: '634' },
  { label: 'Réunion', value: 'RE', code: '638' },
  { label: 'Romania', value: 'RO', code: '642' },
  { label: 'Russian Federation', value: 'RU', code: '643' },
  { label: 'Rwanda', value: 'RW', code: '646' },
  { label: 'Saint Barthélemy', value: 'BL', code: '652' },
  {
    label: 'Saint Helena, Ascension and Tristan da Cunha',
    value: 'SH',
    code: '654'
  },
  { label: 'Saint Kitts and Nevis', value: 'KN', code: '659' },
  { label: 'Saint Lucia', value: 'LC', code: '662' },
  {
    label: 'Saint Martin (French part)',
    value: 'MF',
    code: '663'
  },
  { label: 'Saint Pierre and Miquelon', value: 'PM', code: '666' },
  {
    label: 'Saint Vincent and the Grenadines',
    value: 'VC',
    code: '670'
  },
  { label: 'Samoa', value: 'WS', code: '882' },
  { label: 'San Marino', value: 'SM', code: '674' },
  { label: 'Sao Tome and Principe', value: 'ST', code: '678' },
  { label: 'Saudi Arabia', value: 'SA', code: '682' },
  { label: 'Senegal', value: 'SN', code: '686' },
  { label: 'Serbia', value: 'RS', code: '688' },
  { label: 'Seychelles', value: 'SC', code: '690' },
  { label: 'Sierra Leone', value: 'SL', code: '694' },
  { label: 'Singapore', value: 'SG', code: '702' },
  { label: 'Sint Maarten (Dutch part)', value: 'SX', code: '534' },
  { label: 'Slovakia', value: 'SK', code: '703' },
  { label: 'Slovenia', value: 'SI', code: '705' },
  { label: 'Solomon Islands', value: 'SB', code: '090' },
  { label: 'Somalia', value: 'SO', code: '706' },
  { label: 'South Africa', value: 'ZA', code: '710' },
  {
    label: 'South Georgia and the South Sandwich Islands',
    value: 'GS',
    code: '239'
  },
  { label: 'South Sudan', value: 'SS', code: '728' },
  { label: 'Spain', value: 'ES', code: '724' },
  { label: 'Sri Lanka', value: 'LK', code: '144' },
  { label: 'Sudan', value: 'SD', code: '729' },
  { label: 'Surilabel', value: 'SR', code: '740' },
  { label: 'Svalbard and Jan Mayen', value: 'SJ', code: '744' },
  { label: 'Sweden', value: 'SE', code: '752' },
  { label: 'Switzerland', value: 'CH', code: '756' },
  { label: 'Syrian Arab Republic', value: 'SY', code: '760' },
  { label: 'Taiwan, Province of China', value: 'TW', code: '158' },
  { label: 'Tajikistan', value: 'TJ', code: '762' },
  {
    label: 'Tanzania, United Republic of',
    value: 'TZ',
    code: '834'
  },
  { label: 'Thailand', value: 'TH', code: '764' },
  { label: 'Timor-Leste', value: 'TL', code: '626' },
  { label: 'Togo', value: 'TG', code: '768' },
  { label: 'Tokelau', value: 'TK', code: '772' },
  { label: 'Tonga', value: 'TO', code: '776' },
  { label: 'Trinidad and Tobago', value: 'TT', code: '780' },
  { label: 'Tunisia', value: 'TN', code: '788' },
  { label: 'Türkiye', value: 'TR', code: '792' },
  { label: 'Turkmenistan', value: 'TM', code: '795' },
  { label: 'Turks and Caicos Islands', value: 'TC', code: '796' },
  { label: 'Tuvalu', value: 'TV', code: '798' },
  { label: 'Uganda', value: 'UG', code: '800' },
  { label: 'Ukraine', value: 'UA', code: '804' },
  { label: 'United Arab Emirates', value: 'AE', code: '784' },
  {
    label: 'United Kingdom of Great Britain and Northern Ireland',
    value: 'GB',
    code: '826'
  },
  { label: 'United States of America', value: 'US', code: '840' },
  {
    label: 'United States Minor Outlying Islands',
    value: 'UM',
    code: '581'
  },
  { label: 'Uruguay', value: 'UY', code: '858' },
  { label: 'Uzbekistan', value: 'UZ', code: '860' },
  { label: 'Vanuatu', value: 'VU', code: '548' },
  {
    label: 'Venezuela, Bolivarian Republic of',
    value: 'VE',
    code: '862'
  },
  { label: 'Viet Nam', value: 'VN', code: '704' },
  { label: 'Virgin Islands (British)', value: 'VG', code: '092' },
  { label: 'Virgin Islands (U.S.)', value: 'VI', code: '850' },
  { label: 'Wallis and Futuna', value: 'WF', code: '876' },
  { label: 'Western Sahara', value: 'EH', code: '732' },
  { label: 'Yemen', value: 'YE', code: '887' },
  { label: 'Zambia', value: 'ZM', code: '894' },
  { label: 'Zimbabwe', value: 'ZW', code: '716' }
];

export const languageOptions = [
  {
    label: 'English (US)',
    value: 'en_US'
  },
  {
    label: 'English (UK)',
    value: 'en_GB'
  },
  {
    label: 'Spanish',
    value: 'es'
  },
  {
    label: 'French',
    value: 'fr'
  },
  {
    label: 'German',
    value: 'de'
  }
];
